# Generated by Django 5.2.5 on 2025-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributosEquipo',
            fields=[
                ('id_atributo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('atributo', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'atributos_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('valor_neto', models.IntegerField(blank=True, null=True)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField()),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(default='usuario', max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('direccion_empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('giro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id_estado_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estado_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMantencion',
            fields=[
                ('id_estado_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('rut_proveedor', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_equipo',
                'managed': False,
            },
        ),
    ]
