# Generated by Django 5.2.5 on 2025-09-29 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMantenciones',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('id_mantencion', models.IntegerField()),
                ('fecha_evento', models.DateTimeField()),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario_app_username', models.CharField(blank=True, max_length=150, null=True)),
                ('id_activo', models.IntegerField(blank=True, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=150, null=True)),
                ('activo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_mantencion', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitante_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Mantenciones',
                'verbose_name_plural': 'Historial de Mantenciones',
                'db_table': 'vw_historial_mantenciones',
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(db_column='id_departamento', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('direccion_empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('giro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(db_column='id_factura', primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialMantencionesLog',
            fields=[
                ('id_evento', models.AutoField(db_column='id_evento', primary_key=True, serialize=False)),
                ('id_mantencion', models.IntegerField()),
                ('fecha_evento', models.DateTimeField()),
                ('accion', models.CharField(max_length=30)),
                ('detalle', models.TextField(blank=True, default='')),
                ('usuario_app_username', models.CharField(blank=True, max_length=150, null=True)),
                ('id_activo', models.IntegerField(blank=True, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=150, null=True)),
                ('activo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_mantencion', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable_nombre', models.TextField(blank=True, null=True)),
                ('solicitante_nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de mantenciones (log)',
                'verbose_name_plural': 'Historial de mantenciones (log)',
                'db_table': 'historial_mantenciones_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_activo', models.BooleanField()),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(default='usuario', max_length=20)),
                ('correo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.departamento')),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado', to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa'),
        ),
        migrations.CreateModel(
            name='EstadoActivo',
            fields=[
                ('id_estado_activo', models.AutoField(db_column='id_estado_activo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Estado de activo',
                'verbose_name_plural': 'Estados de activo',
                'db_table': 'estado_activo',
                'managed': True,
                'unique_together': {('id_empresa', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activo', models.AutoField(db_column='id_activo', primary_key=True, serialize=False)),
                ('nombre_activo', models.CharField(max_length=150)),
                ('etiqueta', models.CharField(max_length=150, unique=True)),
                ('qr_code', models.ImageField(blank=True, max_length=1000, null=True, upload_to='qrcodes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('confidencialidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('integridad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disponibilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo_critico', models.BooleanField(default=False)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.departamento')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empleado')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_estado_activo', models.ForeignKey(blank=True, db_column='id_estado_activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.estadoactivo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'activo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoMantencion',
            fields=[
                ('id_estado_mantencion', models.AutoField(db_column='id_estado_mantencion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'db_table': 'estado_mantencion',
                'managed': True,
                'unique_together': {('id_empresa', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(db_column='id_detalle_factura', primary_key=True, serialize=False)),
                ('nombre_activo', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('valor_neto', models.IntegerField(blank=True, null=True)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('id_activo', models.ForeignKey(blank=True, db_column='id_activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.activo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.factura')),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'db_table': 'marca',
                'managed': True,
                'unique_together': {('id_empresa', 'nombre_marca')},
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='id_marca',
            field=models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.marca'),
        ),
        migrations.CreateModel(
            name='PrioridadMantencion',
            fields=[
                ('id_prioridad', models.AutoField(db_column='id_prioridad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Prioridad de mantención',
                'verbose_name_plural': 'Prioridades de mantención',
                'db_table': 'prioridad_mantencion',
                'managed': True,
                'unique_together': {('id_empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('rut_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'managed': True,
                'unique_together': {('id_empresa', 'rut_proveedor')},
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='activo',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.proveedor'),
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id_tipo_activo', models.AutoField(db_column='id_tipo_activo', primary_key=True, serialize=False)),
                ('tipo_activo', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de activo',
                'verbose_name_plural': 'Tipos de activo',
                'db_table': 'tipo_activo',
                'managed': True,
                'unique_together': {('id_empresa', 'tipo_activo')},
            },
        ),
        migrations.CreateModel(
            name='HistorialActivos',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_activo', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(db_column='activo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.activo')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.departamento')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='estado_anterior_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estado_anterior', to='productos.estadoactivo')),
                ('estado_nuevo', models.ForeignKey(blank=True, db_column='estado_nuevo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estado_nuevo', to='productos.estadoactivo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('responsable_actual', models.ForeignKey(blank=True, db_column='responsable_actual_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_actual', to='productos.empleado')),
                ('responsable_anterior_fk', models.ForeignKey(blank=True, db_column='responsable_anterior_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_responsable_anterior', to='productos.empleado')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empleado')),
                ('tipo_activo', models.ForeignKey(blank=True, db_column='tipo_activo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Historial de activos',
                'verbose_name_plural': 'Historial de activos',
                'db_table': 'historial_activos',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AtributosActivo',
            fields=[
                ('id_atributo_activo', models.AutoField(db_column='id_atributo_activo', primary_key=True, serialize=False)),
                ('atributo', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=250, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_tipo_activo', models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Atributo de activo',
                'verbose_name_plural': 'Atributos de activo',
                'db_table': 'atributos_activo',
                'managed': True,
                'unique_together': {('id_tipo_activo', 'atributo')},
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='id_tipo_activo',
            field=models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo'),
        ),
        migrations.CreateModel(
            name='TipoMantencion',
            fields=[
                ('id_tipo_mantencion', models.AutoField(db_column='id_tipo_mantencion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de mantención',
                'verbose_name_plural': 'Tipos de mantención',
                'db_table': 'tipo_mantencion',
                'managed': True,
                'unique_together': {('id_empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(db_column='id_mantencion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.activo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_estado_mantencion', models.ForeignKey(db_column='id_estado_mantencion', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.estadomantencion')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenciones_responsable', to='productos.empleado')),
                ('solicitante_user', models.ForeignKey(blank=True, db_column='solicitante_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('id_prioridad', models.ForeignKey(blank=True, db_column='id_prioridad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.prioridadmantencion')),
                ('id_tipo_mantencion', models.ForeignKey(blank=True, db_column='id_tipo_mantencion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipomantencion')),
            ],
            options={
                'verbose_name': 'Mantención',
                'verbose_name_plural': 'Mantenciones',
                'db_table': 'mantencion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgregacionAtributosPorActivo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.activo')),
                ('atributo', models.ForeignKey(db_column='id_atributo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.atributosactivo')),
            ],
            options={
                'verbose_name': 'Valor de atributo por activo',
                'verbose_name_plural': 'Valores de atributos por activos',
                'db_table': 'agregacion_atributos_por_activo',
                'managed': True,
                'unique_together': {('activo', 'atributo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('id_empresa', 'nombre_departamento')},
        ),
    ]
