# Generated by Django 5.2.5 on 2025-09-30 02:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('productos', '0001_initial'),  # <-- esta es tu última migración real
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # NO toca la base de datos
            state_operations=[
                migrations.AddField(
                    model_name='factura',
                    name='id_empresa',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='productos.empresa',
                        db_column='id_empresa',
                        related_name='facturas',
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
