# Generated by Django 5.2.5 on 2025-09-30 02:22

from django.db import migrations

SQL_FORWARD = """
-- Crea la columna si no existe, en el esquema inventario
ALTER TABLE inventario.factura
  ADD COLUMN IF NOT EXISTS id_empresa integer NULL;

-- Crea la FK si no existe
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints tc
    WHERE tc.constraint_schema = 'inventario'
      AND tc.table_name = 'factura'
      AND tc.constraint_name = 'factura_id_empresa_fkey'
  ) THEN
    ALTER TABLE inventario.factura
      ADD CONSTRAINT factura_id_empresa_fkey
      FOREIGN KEY (id_empresa)
      REFERENCES inventario.empresa(id_empresa)
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END$$;

-- Índice útil para filtrar por empresa (opcional)
CREATE INDEX IF NOT EXISTS idx_factura_empresa ON inventario.factura(id_empresa);
"""

SQL_BACKWARD = """
-- Reverso (opcional). Si no quieres eliminar nada al hacer rollback, deja esto vacío.
DROP INDEX IF EXISTS idx_factura_empresa;
ALTER TABLE inventario.factura DROP CONSTRAINT IF EXISTS factura_id_empresa_fkey;
ALTER TABLE inventario.factura DROP COLUMN IF EXISTS id_empresa;
"""

class Migration(migrations.Migration):
    dependencies = [
        ('productos', '0002_add_id_empresa_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(SQL_FORWARD, reverse_sql=SQL_BACKWARD),
            ],
            state_operations=[]
        ),
    ]
