# Generated by Django 5.2.5 on 2025-09-30 05:48

from django.db import migrations, models
import django.db.models.deletion

SQL = r"""
ALTER TABLE inventario.historial_mantenciones_log
  ADD COLUMN IF NOT EXISTS id_empresa integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'hist_mant_log_id_empresa_fkey'
  ) THEN
    ALTER TABLE inventario.historial_mantenciones_log
      ADD CONSTRAINT hist_mant_log_id_empresa_fkey
      FOREIGN KEY (id_empresa)
      REFERENCES inventario.empresa(id_empresa)
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_hist_mant_log_empresa
  ON inventario.historial_mantenciones_log(id_empresa);
"""

class Migration(migrations.Migration):
    dependencies = [
        ('productos', '0003_add_factura_id_empresa_column_db'),  # o tu última aplicada
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='historialmantencioneslog',   # <--- AJUSTA al nombre real del modelo
                    name='id_empresa',
                    field=models.ForeignKey(
                        db_column='id_empresa',
                        to='productos.empresa',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        blank=True, null=True,
                    ),
                ),
            ],
        ),
    ]
