# Generated by Django 5.2.5 on 2025-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_add_hist_mant_log_id_empresa_db'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='historialmantencioneslog',
#            name='id_empresa',
#        ),
        migrations.AddField(
            model_name='mantencion',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
