# Generated by Django 5.2.5 on 2025-09-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_historialmantencioneslog_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantencioneslog',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa'),
        ),
    ]
