# Generated by Django 5.2.5 on 2025-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_historialmantencioneslog_id_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantencion',
            name='archivo_adjunto',
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
