# Generated by Django 5.2.5 on 2025-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_mantencion_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('confidencial', 'Confidencial'), ('uso_interno', 'Uso Interno'), ('publico', 'Público')], max_length=20, null=True),
        ),
    ]
