# Generated by Django 5.2.5 on 2025-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_activo_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='folio',
            field=models.CharField(blank=True, db_column='folio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='observacion',
            field=models.TextField(blank=True, db_column='observacion', null=True),
        ),
    ]
