# Generated by Django 5.2.5 on 2025-10-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('productos', '0009_factura_folio_factura_observacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id_tipo_registro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de registro',
                'verbose_name_plural': 'Tipos de registro',
                'db_table': 'tipo_registro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.tiporegistro')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'registro',
                'ordering': ['-fecha', '-id_registro'],
            },
        ),
    ]
