# Generated by Django 5.2.5 on 2025-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_tiporegistro_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha', '-id_registro'], 'verbose_name': 'Registro de acción', 'verbose_name_plural': 'Registros de acciones'},
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='datos_antes',
            new_name='datos_anteriores',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='datos_despues',
            new_name='datos_nuevos',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='tipo',
            new_name='tipo_registro',
        ),
        migrations.AddField(
            model_name='registro',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='registro',
            table=None,
        ),
    ]
