# Generated by Django 5.2.5 on 2025-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_remove_registro_eliminado_activo_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributosactivo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
