# Generated by Django 5.2.5 on 2025-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_atributosactivo_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiporegistro',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
