# Generated by Django 5.2.5 on 2025-10-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_registro_eliminado_tiporegistro_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa'),
        ),
        migrations.AddField(
            model_name='tiporegistro',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa'),
        ),
    ]
