# Generated by Django 5.2.5 on 2025-10-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_alter_registro_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialMantenciones',
        ),
    ]
