# Generated by Django 5.2.5 on 2025-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_remove_historial_mantenciones_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, db_index=True, help_text='Número de serie del activo (si aplica).', max_length=120, null=True),
        ),
    ]
