# Generated by Django 5.2.5 on 2025-10-13 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_add_activo_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='asignado',
            field=models.ForeignKey(blank=True, db_column='asignado_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenciones_asignado', to='productos.empleado'),
        ),
    ]
