# Generated by Django 5.2.5 on 2025-10-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_mantencion_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionActivo',
            fields=[
                ('id_condicion_activo', models.AutoField(db_column='id_condicion_activo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Condición de activo',
                'verbose_name_plural': 'Condiciones de activo',
                'db_table': 'condicion_activo',
                'managed': True,
                'unique_together': {('id_empresa', 'descripcion')},
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='id_condicion_activo',
            field=models.ForeignKey(blank=True, db_column='id_condicion_activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.condicionactivo'),
        ),
    ]
