# Generated by Django 5.2.5 on 2025-10-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_condicionactivo_activo_id_condicion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='id_factura',
            field=models.ForeignKey(blank=True, db_column='id_factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.factura', verbose_name='Factura (folio)'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='id_condicion_activo',
            field=models.ForeignKey(blank=True, db_column='id_condicion_activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.condicionactivo', verbose_name='Condición'),
        ),
    ]
