# Generated by Django 5.2.5 on 2025-10-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_activo_id_factura_alter_activo_id_condicion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(db_column='id_modelo', primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.marca')),
                ('id_tipo_activo', models.ForeignKey(blank=True, db_column='id_tipo_activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo')),
            ],
            options={
                'db_table': 'modelo',
                'managed': True,
                'unique_together': {('id_empresa', 'id_tipo_activo', 'nombre_modelo')},
            },
        ),
    ]
