# Generated by Django 5.2.5 on 2025-10-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(db_column='id_ubicacion', primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=255, verbose_name='Nombre de la Ubicación')),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.ubicacion'),
        ),
    ]
