# Generated by Django 5.2.5 on 2025-10-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_ubicacion_empleado_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'managed': True, 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
