# Generated by Django 5.2.5 on 2025-10-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_ubicacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='id_cargo', primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=255, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre_cargo'],
                'managed': True,
                'unique_together': {('id_empresa', 'nombre_cargo')},
            },
        ),
    ]
