# Generated by Django 5.2.5 on 2025-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
