# Generated by Django 5.2.5 on 2025-10-18 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_ubicacion_direccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipoactivo',
            unique_together={('id_empresa', 'tipo_activo')},
        ),
        migrations.AddField(
            model_name='tipoactivo',
            name='estructura_etiqueta',
            field=models.CharField(blank=True, help_text='Abreviación para etiquetas (ej: NBK, IMP, MON).', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Solo letras y números.')], verbose_name='Prefijo de etiqueta'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoactivo',
            unique_together={('id_empresa', 'estructura_etiqueta'), ('id_empresa', 'tipo_activo')},
        ),
    ]
