# Generated by Django 5.2.5 on 2025-10-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_alter_tipoactivo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoOpcionPorTipoActivo',
            fields=[
                ('id_opcion', models.AutoField(db_column='id_opcion', primary_key=True, serialize=False)),
                ('etiqueta_opcion', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('habilitada', models.BooleanField(default=True)),
                ('atributo_definicion', models.ForeignKey(db_column='id_atributo_activo', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.atributosactivo')),
            ],
            options={
                'db_table': 'atributo_opcion_por_tipo_activo',
                'ordering': ['orden', 'etiqueta_opcion'],
                'managed': True,
                'unique_together': {('atributo_definicion', 'etiqueta_opcion')},
            },
        ),
    ]
