# Generated by Django 5.2.5 on 2025-10-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_atributoopcionportipoactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='id_ubicacion',
            field=models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='productos.ubicacion'),
        ),
    ]
