# Generated by Django 5.2.5 on 2025-10-22 15:02

import django.db.models.deletion
import productos.models_inventario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_activo_id_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoActivo',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de documento de activo',
                'verbose_name_plural': 'Tipos de documento de activo',
                'db_table': 'inventario.tipo_documento_activo',
                'unique_together': {('id_empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoActivo',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=productos.models_inventario.documento_activo_upload_to)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='productos.activo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.empresa')),
                ('tipo', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, to='productos.tipodocumentoactivo')),
            ],
            options={
                'verbose_name': 'Documento de activo',
                'verbose_name_plural': 'Documentos de activo',
                'db_table': 'inventario.documento_activo',
                'indexes': [models.Index(fields=['id_activo', 'eliminado'], name='inventario._id_acti_407d4e_idx')],
            },
        ),
    ]
