# Generated by Django 5.2.5 on 2025-10-22 19:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0032_tipodocumentoactivo_documentoactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantencion',
            fields=[
                ('id_plan', models.AutoField(db_column='id_plan', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prealerta_pct', models.PositiveIntegerField(default=10)),
                ('descripcion', models.TextField(blank=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_tipo_activo', models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Plan de mantención',
                'verbose_name_plural': 'Planes de mantención',
                'db_table': 'plan_mantencion',
            },
        ),
        migrations.CreateModel(
            name='PlanMantencionTarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='id_tarea', primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=300)),
                ('obligatorio', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tareas', to='productos.planmantencion')),
            ],
            options={
                'verbose_name': 'Tarea de plan',
                'verbose_name_plural': 'Tareas del plan',
                'db_table': 'plan_mantencion_tarea',
                'ordering': ['orden', 'id_tarea'],
            },
        ),
        migrations.CreateModel(
            name='TipoMedicionActivo',
            fields=[
                ('id_tipo_medicion', models.AutoField(db_column='id_tipo_medicion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='ej: dias, km, horas', max_length=30)),
                ('unidad', models.CharField(help_text='ej: días, km, h', max_length=30)),
                ('es_tiempo', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de medición',
                'verbose_name_plural': 'Tipos de medición',
                'db_table': 'tipo_medicion_activo',
            },
        ),
        migrations.AddField(
            model_name='planmantencion',
            name='tipo_medicion',
            field=models.ForeignKey(db_column='id_tipo_medicion', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipomedicionactivo'),
        ),
        migrations.CreateModel(
            name='MedicionActivo',
            fields=[
                ('id_medicion', models.AutoField(db_column='id_medicion', primary_key=True, serialize=False)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediciones', to='productos.activo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('tipo_medicion', models.ForeignKey(db_column='id_tipo_medicion', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipomedicionactivo')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'db_table': 'medicion_activo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantencionActivo',
            fields=[
                ('id_plan_mantencion_activo', models.AutoField(db_column='id_plan_mantencion_activo', primary_key=True, serialize=False)),
                ('base_fecha', models.DateField(blank=True, null=True)),
                ('base_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ultima_medicion_fecha', models.DateField(blank=True, null=True)),
                ('ultima_medicion_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proximo_vencimiento_fecha', models.DateField(blank=True, null=True)),
                ('proximo_vencimiento_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(blank=True, choices=[('ok', 'Ok'), ('warning', 'Advertencia'), ('overdue', 'Vencido')], default='ok', max_length=12)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='planes', to='productos.activo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, related_name='aplicaciones', to='productos.planmantencion')),
            ],
            options={
                'verbose_name': 'Plan aplicado a Activo',
                'verbose_name_plural': 'Planes aplicados a Activos',
                'db_table': 'plan_mantencion_activo',
                'constraints': [models.UniqueConstraint(fields=('id_plan', 'id_activo'), name='uq_plan_activo_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='tipomedicionactivo',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'codigo'), name='uq_tipomedicion_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='planmantencion',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'id_tipo_activo', 'nombre'), name='uq_plan_empresa_tipo_nombre'),
        ),
    ]
