# Generated by Django 5.2.5 on 2025-10-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0033_planmantencion_planmantenciontarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmantencion',
            name='id_modelo',
            field=models.ForeignKey(blank=True, db_column='id_modelo', help_text='(Opcional) Restringe este plan a un modelo específico.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.modelo'),
        ),
    ]
