# Generated by Django 5.2.5 on 2025-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0034_planmantencion_id_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmantencion',
            name='aplica_a_todos_modelos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planmantencion',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
