# Generated by Django 5.2.5 on 2025-10-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0035_planmantencion_aplica_a_todos_modelos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmantencionactivo',
            name='es_vigente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='planmantencionactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_vigente', True)), fields=('id_activo',), name='uq_un_vigente_por_activo'),
        ),
    ]
