# Generated by Django 5.2.5 on 2025-11-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0036_planmantencionactivo_es_vigente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantencionEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('activo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('empleado_asignado_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('usuario_app_username', models.CharField(blank=True, max_length=150, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('medicion_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medicion_fecha', models.DateField(blank=True, null=True)),
                ('proximo_vencimiento_fecha', models.DateField(blank=True, null=True)),
                ('proximo_vencimiento_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resumen_tareas', models.CharField(blank=True, max_length=500, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('empleado_asignado_fk', models.ForeignKey(blank=True, db_column='empleado_asignado_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.empleado')),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.PROTECT, to='productos.activo')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='productos.empresa')),
                ('id_tipo_activo', models.ForeignKey(blank=True, db_column='id_tipo_activo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.tipoactivo')),
                ('pma', models.ForeignKey(db_column='id_plan_mantencion_activo', on_delete=django.db.models.deletion.PROTECT, to='productos.planmantencionactivo')),
                ('usuario_fk', models.ForeignKey(blank=True, db_column='usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de mantención (PMA)',
                'verbose_name_plural': 'Ejecuciones de mantención (PMA)',
                'db_table': 'inventario.pma_historial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MantencionEjecucionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('obligatorio', models.BooleanField(default=False)),
                ('marcada', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ejecucion', models.ForeignKey(db_column='id_ejecucion', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='productos.mantencionejecucion')),
                ('id_tarea_plan', models.ForeignKey(db_column='id_tarea_plan', on_delete=django.db.models.deletion.PROTECT, to='productos.planmantenciontarea')),
            ],
            options={
                'verbose_name': 'Tarea ejecutada (PMA)',
                'verbose_name_plural': 'Tareas ejecutadas (PMA)',
                'db_table': 'inventario.pma_historial_tarea',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='mantencionejecucion',
            index=models.Index(fields=['id_empresa', '-fecha_ejecucion'], name='pma_hist_emp_fech_idx'),
        ),
        migrations.AddIndex(
            model_name='mantencionejecucion',
            index=models.Index(fields=['id_activo'], name='pma_hist_act_idx'),
        ),
        migrations.AddIndex(
            model_name='mantencionejecucion',
            index=models.Index(fields=['pma'], name='pma_hist_pma_idx'),
        ),
        migrations.AddIndex(
            model_name='mantencionejecuciontarea',
            index=models.Index(fields=['ejecucion'], name='pma_hist_tarea_ejec_idx'),
        ),
        migrations.AddIndex(
            model_name='mantencionejecuciontarea',
            index=models.Index(fields=['id_tarea_plan'], name='pma_hist_tarea_plan_idx'),
        ),
    ]
