# Generated by Django 5.2.5 on 2025-11-10 13:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0037_mantencionejecucion_mantencionejecuciontarea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencionejecucion',
            options={'managed': True, 'ordering': ['-fecha_ejecucion', '-id'], 'verbose_name': 'Ejecución de mantención (PMA)', 'verbose_name_plural': 'Ejecuciones de mantención (PMA)'},
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(django.db.models.functions.text.Trim(django.db.models.functions.text.Lower('nombre_proveedor')), name='ix_prov_nombre_norm'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Trim(django.db.models.functions.text.Lower('nombre_proveedor')), models.F('id_empresa'), condition=models.Q(('eliminado', False)), name='uniq_proveedor_nombre_empresa_ci_active'),
        ),
    ]
