# Generated by Django 5.2.5 on 2025-11-10 15:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0038_alter_mantencionejecucion_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre_cargo'), models.F('id_empresa'), name='uniq_cargo_empresa_lower'),
        ),
    ]
