# Generated by Django 5.2.5 on 2025-11-13 17:45

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0039_cargo_uniq_cargo_empresa_lower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoNota',
            fields=[
                ('id_nota', models.AutoField(db_column='id_nota', primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('texto', models.TextField()),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activo_nota',
                'ordering': ['-creado_en', '-id_nota'],
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='cargo',
            name='uniq_cargo_empresa_lower',
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre_cargo'), models.F('id_empresa'), condition=models.Q(('eliminado', False)), name='uniq_cargo_empresa_lower_active', violation_error_message='Ya existe un cargo con ese nombre en esta empresa.'),
        ),
        migrations.AddField(
            model_name='activonota',
            name='id_activo',
            field=models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas', to='productos.activo'),
        ),
        migrations.AddField(
            model_name='activonota',
            name='id_autor',
            field=models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empleado'),
        ),
        migrations.AddField(
            model_name='activonota',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa'),
        ),
        migrations.AddIndex(
            model_name='activonota',
            index=models.Index(fields=['id_activo', '-creado_en'], name='ix_nota_activo_fecha'),
        ),
        migrations.AddIndex(
            model_name='activonota',
            index=models.Index(fields=['id_empresa', 'id_activo'], name='ix_nota_empresa_activo'),
        ),
    ]
