# Generated by Django 5.2.5 on 2025-11-14 11:53

import django.core.validators
import productos.models_inventario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0040_activonota_remove_cargo_uniq_cargo_empresa_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activonota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models_inventario.nota_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), productos.models_inventario.validate_image_size], verbose_name='Foto adjunta'),
        ),
    ]
