# Generated by Django 5.2.5 on 2025-11-15 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0041_activonota_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaCriticidad',
            fields=[
                ('id_regla', models.AutoField(db_column='id_regla', primary_key=True, serialize=False)),
                ('cargo_nombre', models.CharField(blank=True, help_text='Nombre del cargo tal como aparece en Empleado.cargo', max_length=100, null=True)),
                ('confidencialidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('integridad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('disponibilidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('clasificacion', models.CharField(blank=True, choices=[('confidencial', 'Confidencial'), ('uso_interno', 'Uso Interno'), ('publico', 'Público')], max_length=20, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_tipo_activo', models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Regla de criticidad',
                'verbose_name_plural': 'Reglas de criticidad',
                'db_table': 'regla_criticidad',
                'managed': True,
                'unique_together': {('id_empresa', 'id_tipo_activo', 'cargo_nombre')},
            },
        ),
    ]
