# Generated by Django 5.2.5 on 2025-11-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0042_reglacriticidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionAsignacion',
            fields=[
                ('id_preparacion', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(help_text='Nombre del cargo tal como se usa en Empleado.cargo', max_length=150)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('habilitada', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_asignacion', to='productos.empresa')),
                ('id_tipo_activo', models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_asignacion', to='productos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Preparación de asignación',
                'verbose_name_plural': 'Preparaciones de asignación',
                'db_table': 'preparacion_asignacion',
                'unique_together': {('id_empresa', 'id_tipo_activo', 'cargo')},
            },
        ),
        migrations.CreateModel(
            name='AccionPreparacion',
            fields=[
                ('id_accion_preparacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text="Ej: 'Instalar Windows', 'Configurar antivirus', etc.", max_length=255)),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio, debe marcarse el check para poder asignar.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_preparacion', models.ForeignKey(db_column='id_preparacion', on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='productos.preparacionasignacion')),
            ],
            options={
                'verbose_name': 'Acción de preparación',
                'verbose_name_plural': 'Acciones de preparación',
                'db_table': 'accion_preparacion',
                'ordering': ['orden', 'id_accion_preparacion'],
            },
        ),
    ]
