# Generated by Django 5.2.5 on 2025-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0043_preparacionasignacion_accionpreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionactivo',
            name='codigo_sistema',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código sistema'),
        ),
    ]
