# Generated by Django 5.2.5 on 2025-11-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0044_condicionactivo_codigo_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionDetalle',
            fields=[
                ('id_condicion_detalle', models.AutoField(db_column='id_condicion_detalle', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('condicion_activo', models.ForeignKey(db_column='id_condicion_activo', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='productos.condicionactivo')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
            ],
            options={
                'verbose_name': 'Detalle de condición',
                'verbose_name_plural': 'Detalles de condición',
                'db_table': 'condicion_detalle',
                'managed': True,
                'unique_together': {('id_empresa', 'descripcion')},
            },
        ),
    ]
