# Generated by Django 5.2.5 on 2025-11-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0045_condiciondetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'managed': True, 'ordering': ('-id_detalle_factura',)},
        ),
        migrations.AlterModelOptions(
            name='planmantencionactivo',
            options={'ordering': ['-id_plan_mantencion_activo'], 'verbose_name': 'Plan aplicado a Activo', 'verbose_name_plural': 'Planes aplicados a Activos'},
        ),
    ]
