# Generated by Django 5.2.5 on 2025-11-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0046_alter_detallefactura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='id_condicion_detalle',
            field=models.ForeignKey(blank=True, db_column='id_condicion_detalle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.condiciondetalle', verbose_name='Condición_Activo'),
        ),
    ]
