# Generated by Django 5.2.5 on 2025-11-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0047_activo_id_condicion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='id_detalle_factura',
            field=models.ForeignKey(blank=True, db_column='id_detalle_factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activos', to='productos.detallefactura', verbose_name='Detalle de factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_iva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_neto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id_activo',
            field=models.ForeignKey(blank=True, db_column='id_activo', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.activo'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id_factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='productos.factura'),
        ),
    ]
