# Generated by Django 5.2.5 on 2025-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0048_activo_id_detalle_factura_factura_monto_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='trabajador', max_length=20),
        ),
    ]
