# Generated by Django 5.2.5 on 2025-12-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0049_alter_empleado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(db_column='id_bodega', primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=150, verbose_name='Nombre de la bodega')),
                ('es_principal', models.BooleanField(default=False, help_text='Si está marcada, es la bodega por defecto de la empresa.')),
                ('eliminado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.empresa')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_fisicas', to='productos.ubicacion', verbose_name='Ubicación física')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
            },
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='id_bodega_retorno',
            field=models.ForeignKey(blank=True, db_column='id_bodega_retorno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_origen', to='productos.bodega', verbose_name='Bodega de retorno'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'nombre_bodega'), name='uniq_bodega_empresa_nombre'),
        ),
    ]
