# Generated by Django 5.2.5 on 2025-12-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0050_bodega_ubicacion_id_bodega_retorno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoBodega',
            fields=[
                ('id_permiso_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuarios', to='productos.bodega')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_bodega', to='productos.empleado')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.empresa')),
            ],
            options={
                'db_table': 'permiso_bodega',
                'unique_together': {('id_empleado', 'id_bodega')},
            },
        ),
    ]
